[package]
name = "client"
version = "0.1.0"
edition = "2024"

[features]
default = ["tracing"]
tracing = []

[dependencies]
netlib = {path = "../netlib"}
tokio = { version = "1.49.0", features = ["full"] }
bytes = "1.11.1"
tracing = "0.1"
tracing-subscriber = "0.3"
