[package]
name = "engine"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.11.1"
circular-buffer = "1.2.0"
fastrand = "2.3.0"
netlib = {path = "../netlib"}
nexus-queue = "1.0.0"
rand = "0.10.0"
rand_chacha = "0.10.0"
rand_distr = "0.6.0"
smallrand = "1.0.1"
zerocopy = { version = "0.8.39", features = ["derive"] }