[package]
name = "engine"
version = "0.1.0"
edition = "2024"

[features]
default = ["tracing"]
tracing = []

[dependencies]
netlib = {path = "../netlib"}
tokio = { version = "1.49.0", features = ["full"] }
bytes = "1.11.1"
circular-buffer = "1.2.0"
fastrand = "2.3.0"
rand = "0.10.0"
rand_chacha = "0.10.0"
rand_distr = "0.6.0"
smallrand = "1.0.1"
tracing = "0.1"
tracing-subscriber = "0.3"
